### ISSUE TITLE
Logging still active in production?

### ISSUE THREAD

**Issue by jhogervorst** [Treast/kirby-debugbar#8] opened 2024-05-17 11:19 UTC
After quickly looking through your code, it looks like the `debug` (and `force`) options only control whether the debugbar is displayed (in the snippet). The logging itself seems to be always active, even if the debugbar is not displayed.

Wouldn't it be better for performance in production to disable the logging completely?

**Comment by Treast** [comment] 2024-05-27 17:48
Hello,

Thanks for the feedback. You're totally right.

The issue is resolved in commit https://github.com/Treast/kirby-debugbar/commit/138a64554b1d07825fff98bd9e43a0221f1662fa and a new release v1.3.3 is available with the fix.

**Closed as completed by Treast** 2024-05-27 17:48 UTC
Labels: enhancement
